name: Publish Package

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  package_publish_framework:
    name: Package & Publish NuGet Package
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup .NET v8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: NuGet Package Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-NuGet-RockHopper
          restore-keys: |
            ${{ runner.os }}-NuGet-RockHopper

      #- name: Restore Project
      #  shell: bash
      #  run: dotnet restore
#
      - name: Build Project (net8.0)
        shell: bash
        run: dotnet build -p:TargetFramework=net8.0 --configuration Release

      - name: Build Project (net9.0)
        shell: bash
        run: dotnet build -p:TargetFramework=net9.0 --configuration Release
        
      - name: Package Project
        shell: bash
        run: |
          tag=${{ github.ref }}
          version="${tag##*/v}"   
          cd src/RockHopper
          dotnet pack -p:PackageVersion=$version --configuration Release